# Generated by Django 4.1.6 on 2023-02-09 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('number', models.PositiveIntegerField()),
                ('type', models.CharField(choices=[('A', 'Asset'), ('L', 'Liability'), ('I', 'Income'), ('E', 'Expense'), ('Q', 'Equity')], max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('party', models.CharField(max_length=200)),
                ('source', models.CharField(max_length=200)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('description', models.CharField(max_length=200)),
                ('is_closed', models.BooleanField()),
                ('date_closed', models.DateField()),
            ],
        ),
    ]
