# Generated by Django 5.1.4 on 2025-01-02 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="s3file",
            name="analysis_complete",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
