# Generated by Django 5.1.4 on 2025-01-02 01:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='s3file',
            name='analysis_complete',
        ),
    ]
