# Generated by Django 5.1.4 on 2025-02-02 01:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_entity_is_closed'),
    ]

    operations = [
        migrations.AddField(
            model_name='autotag',
            name='entity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.entity'),
        ),
    ]
