# Generated by Django 4.1.6 on 2023-02-10 13:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_transaction_category_alter_account_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='number',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='party',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='source',
        ),
        migrations.AddField(
            model_name='transaction',
            name='account',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='api.account'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='transaction',
            name='date_closed',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='is_closed',
            field=models.BooleanField(default=False),
        ),
    ]
