# Generated by Django 5.1.4 on 2025-02-02 16:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_transaction_suggested_entity'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='entity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='accounts', to='api.entity'),
        ),
    ]
