# Generated by Django 4.1.6 on 2023-02-10 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_transaction_date_closed'),
    ]

    operations = [
        migrations.RenameField(
            model_name='journalentry',
            old_name='journal_entry',
            new_name='transaction',
        ),
        migrations.AlterField(
            model_name='journalentry',
            name='description',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
