# Generated by Django 5.1.4 on 2025-02-03 00:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_account_entity'),
    ]

    operations = [
        migrations.AddField(
            model_name='prefillitem',
            name='entity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='prefill_item', to='api.entity'),
        ),
    ]
