# Generated by Django 4.1.6 on 2023-02-10 15:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_rename_journal_entry_journalentry_transaction_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='JournalEntryItems',
            new_name='JournalEntryItem',
        ),
        migrations.RenameField(
            model_name='journalentryitem',
            old_name='journel_entry',
            new_name='journal_entry',
        ),
    ]
