# Generated by Django 5.1.4 on 2025-02-04 00:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_prefillitem_entity'),
    ]

    operations = [
        migrations.AddField(
            model_name='docsearch',
            name='entity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='docsearches', to='api.entity'),
        ),
        migrations.AddField(
            model_name='paystubvalue',
            name='entity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='paystubvalues', to='api.entity'),
        ),
    ]
