# Generated by Django 4.1.6 on 2023-02-10 15:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_rename_journalentryitems_journalentryitem_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journalentryitem',
            name='journal_entry',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='journal_entry_items', to='api.journalentry'),
        ),
        migrations.AlterField(
            model_name='journalentryitem',
            name='type',
            field=models.CharField(choices=[('debit', 'Debit'), ('credit', 'Credit')], max_length=6),
        ),
    ]
