# Generated by Django 5.1.4 on 2025-04-04 00:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_docsearch_entity_paystubvalue_entity'),
    ]

    operations = [
        migrations.AddField(
            model_name='amortization',
            name='entity',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='amortizations', to='api.entity'),
        ),
    ]
