# Generated by Django 4.1.6 on 2023-02-12 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_alter_account_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='sub_type',
            field=models.CharField(choices=[('credit_card', 'Credit Card')], default='credit_card', max_length=30),
            preserve_default=False,
        ),
    ]
