# Generated by Django 5.1.4 on 2025-08-16 18:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0010_alter_entity_options_alter_account_special_type_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="account",
            name="tax_payable_account",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="api.account",
            ),
        ),
        migrations.AddField(
            model_name="taxcharge",
            name="account",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="tax_charges",
                to="api.account",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="taxcharge",
            unique_together={("account", "date")},
        ),
        migrations.RemoveField(
            model_name="taxcharge",
            name="type",
        ),
    ]
