# Generated by Django 4.1.6 on 2023-02-13 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_account_sub_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='AutoTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('search_string', models.CharField(max_length=20)),
                ('accounts', models.ManyToManyField(to='api.account')),
            ],
        ),
    ]
