# Generated by Django 5.1.4 on 2025-08-16 18:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_alter_taxcharge_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='taxcharge',
            unique_together=set(),
        ),
    ]
