# Generated by Django 4.1.6 on 2023-02-13 18:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_autotag'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='autotag',
            name='accounts',
        ),
        migrations.AddField(
            model_name='autotag',
            name='account',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='api.account'),
            preserve_default=False,
        ),
    ]
