# Generated by Django 5.1.4 on 2025-08-16 18:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_alter_taxcharge_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='taxcharge',
            unique_together={('account', 'date')},
        ),
    ]
