# Generated by Django 5.1.4 on 2025-08-21 00:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_alter_taxcharge_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taxcharge',
            name='account',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='tax_charges', to='api.account'),
            preserve_default=False,
        ),
    ]
