# Generated by Django 4.1.6 on 2023-02-13 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_transaction_suggested_account'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='suggested_type',
            field=models.CharField(blank=True, max_length=8),
        ),
        migrations.AddField(
            model_name='transaction',
            name='type',
            field=models.CharField(blank=True, max_length=8),
        ),
    ]
