# Generated by Django 5.1.4 on 2025-09-28 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_alter_taxcharge_account'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='tax_amount',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Flat tax amount (e.g., 1000.00)', max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='account',
            name='tax_rate',
            field=models.DecimalField(blank=True, decimal_places=4, help_text='Tax rate as a decimal (e.g., 0.3110 for 31.10%)', max_digits=4, null=True),
        ),
    ]
