# Generated by Django 5.1.4 on 2025-10-16 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_account_tax_amount_account_tax_rate'),
    ]

    operations = [
        migrations.AddField(
            model_name='prefill',
            name='is_closed',
            field=models.BooleanField(default=False),
        ),
    ]
