# Generated by Django 4.1.6 on 2023-02-14 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_alter_transaction_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='autotag',
            name='transaction_type',
            field=models.CharField(blank=True, choices=[('income', 'Income'), ('purchase', 'Purchase'), ('payment', 'Payment'), ('transfer', 'Transfer')], max_length=25),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='suggested_type',
            field=models.CharField(blank=True, choices=[('income', 'Income'), ('purchase', 'Purchase'), ('payment', 'Payment'), ('transfer', 'Transfer')], max_length=25),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='type',
            field=models.CharField(blank=True, choices=[('income', 'Income'), ('purchase', 'Purchase'), ('payment', 'Payment'), ('transfer', 'Transfer')], max_length=25),
        ),
    ]
