# Generated by Django 5.1.4 on 2025-11-08 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_prefill_is_closed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='special_type',
            field=models.CharField(blank=True, choices=[('unrealized_gains_and_losses', 'Unrealized Gains and Losses'), ('state_taxes_payable', 'State Taxes Payable'), ('federal_taxes_payable', 'Federal Taxes Payable'), ('property_taxes_payable', 'Property Taxes Payable'), ('state_taxes', 'State Taxes'), ('federal_taxes', 'Federal Taxes'), ('property_taxes', 'Property Taxes'), ('wallet', 'Wallet'), ('prepaid_expenses', 'Prepaid Expenses'), ('starting_equity', 'Starting Equity')], max_length=30, null=True),
        ),
    ]
