# Generated by Django 5.1.4 on 2025-11-08 21:40

import api.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_alter_account_special_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journalentryitem',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=12, validators=[api.validators.non_zero]),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=12, validators=[api.validators.non_zero]),
        ),
    ]
