# Generated by Django 4.1.6 on 2023-02-16 12:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_csvprofile_account_csv_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='linked_transaction',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.transaction'),
        ),
    ]
