# Generated by Django 5.1.4 on 2026-02-15 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_alter_journalentryitem_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='journalentry',
            name='created_by',
            field=models.CharField(default='user', max_length=100),
        ),
    ]
