# Generated by Django 4.1.6 on 2023-02-19 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_transaction_linked_transaction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='sub_type',
            field=models.CharField(choices=[('credit_card', 'Credit Card'), ('loan', 'Loan'), ('cash', 'Cash'), ('real_estate', 'Real Estate'), ('securities', 'Securities'), ('retained_earnings', 'Retained Earnings'), ('investment_gains', 'Investment Gains')], max_length=30),
        ),
    ]
