# Generated by Django 4.1.6 on 2023-02-21 23:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_alter_account_sub_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='csv_profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='accounts', to='api.csvprofile'),
        ),
        migrations.AlterField(
            model_name='account',
            name='sub_type',
            field=models.CharField(choices=[('credit_card', 'Credit Card'), ('loan', 'Loan'), ('cash', 'Cash'), ('real_estate', 'Real Estate'), ('securities', 'Securities'), ('retained_earnings', 'Retained Earnings'), ('investment_gains', 'Investment Gains'), ('income', 'Income'), ('purchases', 'Purchases')], max_length=30),
        ),
    ]
