# Generated by Django 6.0.4 on 2026-04-22 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_s3file_error_message_s3file_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='amortization',
            name='salvage_value',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
    ]
