# Generated by Django 4.1.6 on 2023-02-23 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_alter_transaction_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='default_transaction_type',
            field=models.CharField(blank=True, choices=[('income', 'Income'), ('purchase', 'Purchase'), ('payment', 'Payment'), ('transfer', 'Transfer')], max_length=25),
        ),
    ]
