# Generated by Django 6.0.4 on 2026-04-22 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_alter_account_sub_type'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='account',
            name='unique_special_type_except_property_taxes',
        ),
        migrations.AddConstraint(
            model_name='account',
            constraint=models.UniqueConstraint(condition=models.Q(('special_type__in', ['property_taxes', 'prepaid_expenses']), _negated=True), fields=('special_type',), name='unique_special_type_except_property_taxes'),
        ),
    ]
