# Generated by Django 4.1.6 on 2023-02-25 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0024_remove_account_default_transaction_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='csvprofile',
            name='account',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
