# Generated by Django 6.0.4 on 2026-06-09 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0025_rename_purchases_to_operating_subtype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='csvprofile',
            name='clear_values_column_pairs',
            field=models.ManyToManyField(blank=True, to='api.csvcolumnvaluepair'),
        ),
    ]
