# Generated by Django 6.0.4 on 2026-06-10 15:10

from django.db import migrations, models


def migrate_depreciation_subtype_to_flag(apps, schema_editor):
    """Move accounts off the removed 'depreciation' sub_type onto the flag.

    Depreciation is an operating expense, so reassign the sub_type to
    'operating' and mark is_depreciation=True so the cash flow statement keeps
    classifying it as a depreciation add-back.
    """
    Account = apps.get_model('api', 'Account')
    Account.objects.filter(sub_type='depreciation').update(
        sub_type='operating', is_depreciation=True
    )


def reverse_depreciation_flag_to_subtype(apps, schema_editor):
    Account = apps.get_model('api', 'Account')
    Account.objects.filter(is_depreciation=True).update(sub_type='depreciation')


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0026_alter_csvprofile_clear_values_column_pairs'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='is_depreciation',
            field=models.BooleanField(default=False, help_text='Marks an expense account as depreciation. Depreciation draws a depreciable asset down without moving cash, so the cash flow statement adds it back to operations and keeps it out of investing.'),
        ),
        migrations.RunPython(
            migrate_depreciation_subtype_to_flag,
            reverse_depreciation_flag_to_subtype,
        ),
        migrations.AlterField(
            model_name='account',
            name='sub_type',
            field=models.CharField(choices=[('short_term_debt', 'Short-term Debt'), ('taxes_payable', 'Taxes Payable'), ('long_term_debt', 'Long-term Debt'), ('cash', 'Cash'), ('accounts_receivable', 'Accounts Receivable'), ('prepaid_expenses', 'Prepaid Expenses'), ('securities_unrestricted', 'Securities-Unrestricted'), ('securities_retirement', 'Securities-Retirement'), ('real_estate', 'Real Estate'), ('vehicles', 'Vehicles'), ('retained_earnings', 'Retained Earnings'), ('salary', 'Salary'), ('dividends_and_interest', 'Dividends & Interest'), ('realized_investment_gains', 'Realized Investment Gains'), ('other_income', 'Other Income'), ('unrealized_investment_gains', 'Unrealized Investment Gains'), ('operating', 'Operating'), ('tax', 'Tax'), ('interest', 'Interest Expense')], max_length=30),
        ),
    ]
