# Generated by Django 6.0.4 on 2026-06-14 14:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0027_account_is_depreciation_alter_account_sub_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='docsearch',
            name='selection',
            field=models.CharField(blank=True, choices=[('Company', 'Company'), ('Begin Period', 'Begin Period'), ('End Period', 'End Period'), ('Vendor', 'Vendor'), ('Account Number', 'Account Number'), ('Amount Due', 'Amount Due'), ('Service Address', 'Service Address'), ('Bill Date', 'Bill Date'), ('Due Date', 'Due Date')], max_length=20, null=True),
        ),
        migrations.CreateModel(
            name='UtilityBillRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_address', models.CharField(max_length=200)),
                ('subject', models.CharField(max_length=200)),
                ('account_number', models.CharField(max_length=100)),
                ('address_hint', models.CharField(blank=True, max_length=200)),
                ('transaction_description_match', models.CharField(max_length=200)),
                ('transaction_type', models.CharField(choices=[('income', 'Income'), ('purchase', 'Purchase'), ('payment', 'Payment'), ('transfer', 'Transfer')], default='purchase', max_length=25)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.account')),
                ('entity', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='utility_bill_rules', to='api.entity')),
                ('prefill', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.prefill')),
            ],
        ),
        migrations.CreateModel(
            name='UtilityBill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_message_id', models.CharField(max_length=200, unique=True)),
                ('from_address', models.CharField(blank=True, max_length=200)),
                ('subject', models.CharField(blank=True, max_length=500)),
                ('raw_text', models.TextField(blank=True)),
                ('received_at', models.DateTimeField(blank=True, null=True)),
                ('vendor', models.CharField(blank=True, max_length=200)),
                ('account_number', models.CharField(blank=True, max_length=100)),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('service_address', models.CharField(blank=True, max_length=200)),
                ('bill_date', models.DateField(blank=True, null=True)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('parsed', 'Parsed'), ('unresolved', 'Unresolved'), ('matched', 'Matched'), ('failed', 'Failed')], default='pending', max_length=25)),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='utility_bills', to='api.account')),
                ('entity', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='utility_bills', to='api.entity')),
                ('matched_transaction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='utility_bills', to='api.transaction')),
                ('rule', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.utilitybillrule')),
            ],
        ),
    ]
