# Generated by Django 6.0.4 on 2026-06-14 14:09

from django.db import migrations

# The "Utility Bill" Prefill drives Gemini extraction for forwarded utility
# bill emails. One Prefill serves every vendor since the field set is uniform.
PREFILL_NAME = "Utility Bill"

# (selection label, keyword hint) for each metadata field to extract.
BILL_DOC_SEARCHES = [
    ("Vendor", "the utility company / biller name"),
    ("Account Number", "Account Number"),
    ("Amount Due", "Amount Due"),
    ("Service Address", "Service Address"),
    ("Bill Date", "Bill Date"),
    ("Due Date", "Due Date"),
]


def create_utility_bill_prefill(apps, schema_editor):
    Prefill = apps.get_model("api", "Prefill")
    DocSearch = apps.get_model("api", "DocSearch")

    prefill, _ = Prefill.objects.get_or_create(name=PREFILL_NAME)

    for selection, keyword in BILL_DOC_SEARCHES:
        DocSearch.objects.get_or_create(
            prefill=prefill,
            selection=selection,
            defaults={"keyword": keyword},
        )


def remove_utility_bill_prefill(apps, schema_editor):
    Prefill = apps.get_model("api", "Prefill")
    DocSearch = apps.get_model("api", "DocSearch")

    DocSearch.objects.filter(prefill__name=PREFILL_NAME).delete()
    Prefill.objects.filter(name=PREFILL_NAME).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0028_alter_docsearch_selection_utilitybillrule_and_more'),
    ]

    operations = [
        migrations.RunPython(
            create_utility_bill_prefill, remove_utility_bill_prefill
        ),
    ]
