# Generated by Django 6.0.4 on 2026-06-14 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0029_seed_utility_bill_prefill'),
    ]

    operations = [
        migrations.AddField(
            model_name='utilitybill',
            name='payment_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='docsearch',
            name='selection',
            field=models.CharField(blank=True, choices=[('Company', 'Company'), ('Begin Period', 'Begin Period'), ('End Period', 'End Period'), ('Vendor', 'Vendor'), ('Account Number', 'Account Number'), ('Amount Due', 'Amount Due'), ('Service Address', 'Service Address'), ('Bill Date', 'Bill Date'), ('Due Date', 'Due Date'), ('Payment Date', 'Payment Date')], max_length=20, null=True),
        ),
    ]
