# Generated by Django 6.0.4 on 2026-06-14 18:58

from django.db import migrations

PREFILL_NAME = "Utility Bill"
SELECTION = "Payment Date"
KEYWORD = "Payment Date"


def add_payment_date_docsearch(apps, schema_editor):
    Prefill = apps.get_model("api", "Prefill")
    DocSearch = apps.get_model("api", "DocSearch")

    prefill = Prefill.objects.filter(name=PREFILL_NAME).first()
    if prefill is None:
        return
    DocSearch.objects.get_or_create(
        prefill=prefill,
        selection=SELECTION,
        defaults={"keyword": KEYWORD},
    )


def remove_payment_date_docsearch(apps, schema_editor):
    DocSearch = apps.get_model("api", "DocSearch")
    DocSearch.objects.filter(
        prefill__name=PREFILL_NAME, selection=SELECTION
    ).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0030_utilitybill_payment_date_alter_docsearch_selection'),
    ]

    operations = [
        migrations.RunPython(
            add_payment_date_docsearch, remove_payment_date_docsearch
        ),
    ]
