# Generated by Django 6.0.4 on 2026-06-14 19:03

from django.db import migrations

PREFILL_NAME = "Utility Bill"
OLD_KEYWORD = "Amount Due"
# Utility emails label the amount differently ("Amount Due" on bills,
# "Payment Amount" on payment confirmations). A combined hint lets Gemini find
# the value reliably regardless of which email type is configured.
NEW_KEYWORD = "Payment Amount or Amount Due (the total dollar amount)"


def _set_keyword(apps, keyword):
    DocSearch = apps.get_model("api", "DocSearch")
    DocSearch.objects.filter(
        prefill__name=PREFILL_NAME, selection="Amount Due"
    ).update(keyword=keyword)


def broaden(apps, schema_editor):
    _set_keyword(apps, NEW_KEYWORD)


def revert(apps, schema_editor):
    _set_keyword(apps, OLD_KEYWORD)


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0031_add_payment_date_docsearch'),
    ]

    operations = [
        migrations.RunPython(broaden, revert),
    ]
