# Generated by Django 4.1.6 on 2023-03-06 23:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0032_alter_account_sub_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='linked_transaction',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='api.transaction'),
        ),
    ]
