# Generated by Django 6.0.4 on 2026-06-15 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0032_broaden_amount_docsearch_hint'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='utilitybillrule',
            name='prefill',
        ),
        migrations.AlterField(
            model_name='docsearch',
            name='selection',
            field=models.CharField(blank=True, choices=[('Company', 'Company'), ('Begin Period', 'Begin Period'), ('End Period', 'End Period')], max_length=20, null=True),
        ),
    ]
