# Generated by Django 6.0.4 on 2026-06-15 00:24
#
# Utility-bill extraction no longer uses DocSearch/Prefill config (the field
# set is fixed in code). Remove the seeded "Utility Bill" Prefill and its
# DocSearch rows created by migrations 0029/0031/0032.
from django.db import migrations

PREFILL_NAME = "Utility Bill"


def remove_utility_bill_prefill(apps, schema_editor):
    Prefill = apps.get_model("api", "Prefill")
    DocSearch = apps.get_model("api", "DocSearch")

    DocSearch.objects.filter(prefill__name=PREFILL_NAME).delete()
    Prefill.objects.filter(name=PREFILL_NAME).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0033_drop_utilitybillrule_prefill'),
    ]

    operations = [
        # Forward-only cleanup; the prefill is reseeded by 0029 on a fresh DB
        # before this runs, then removed here.
        migrations.RunPython(
            remove_utility_bill_prefill, migrations.RunPython.noop
        ),
    ]
