# Generated by Django 4.1.6 on 2023-03-07 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0033_alter_transaction_linked_transaction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='sub_type',
            field=models.CharField(choices=[('short_term_debt', 'Short-term Debt'), ('long_term_debt', 'Long-term Debt'), ('taxes_payable', 'Taxes Payable'), ('cash', 'Cash'), ('real_estate', 'Real Estate'), ('securities_retirement', 'Securities-Retirement'), ('securities_unrestricted', 'Securities-Unrestricted'), ('retained_earnings', 'Retained Earnings'), ('investment_gains', 'Investment Gains'), ('salary', 'Salary'), ('dividends_and_interest', 'Dividends & Interest'), ('other_income', 'Other Income'), ('purchases', 'Purchases'), ('tax', 'Tax')], max_length=30),
        ),
    ]
