# Generated by Django 6.0.4 on 2026-06-15 18:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0034_remove_utility_bill_prefill_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='Loan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('original_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('annual_interest_rate', models.DecimalField(decimal_places=4, max_digits=6)),
                ('term_months', models.PositiveSmallIntegerField()),
                ('start_date', models.DateField()),
                ('payment_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('description_match', models.CharField(blank=True, max_length=200)),
                ('date_window_days', models.PositiveSmallIntegerField(default=7)),
                ('is_closed', models.BooleanField(default=False)),
                ('entity', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='loans', to='api.entity')),
                ('interest_account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='loans_interest', to='api.account')),
                ('payment_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='loans_payment', to='api.account')),
                ('principal_account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='loans_principal', to='api.account')),
            ],
        ),
        migrations.CreateModel(
            name='LoanPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sequence', models.PositiveSmallIntegerField()),
                ('date', models.DateField()),
                ('payment_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('principal_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('interest_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('remaining_balance', models.DecimalField(decimal_places=2, max_digits=12)),
                ('kind', models.CharField(choices=[('scheduled', 'Scheduled'), ('principal_only', 'Principal-only'), ('payoff', 'Payoff')], default='scheduled', max_length=20)),
                ('loan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='api.loan')),
                ('transaction', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='loan_payment', to='api.transaction')),
            ],
            options={
                'ordering': ['loan', 'sequence'],
            },
        ),
    ]
