# Generated by Django 6.0.4 on 2026-06-15 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0035_loan_loanpayment'),
    ]

    operations = [
        migrations.AddField(
            model_name='loanpayment',
            name='balance_override',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
    ]
