# Generated by Django 6.0.6 on 2026-06-29 15:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0036_loanpayment_balance_override'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecharacterizeChange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('action_kind', models.CharField(max_length=20)),
                ('action_summary', models.CharField(max_length=255)),
                ('criteria_summary', models.TextField(blank=True)),
                ('updated_count', models.PositiveIntegerField(default=0)),
                ('is_reverted', models.BooleanField(default=False)),
                ('reverted_at', models.DateTimeField(blank=True, null=True)),
                ('new_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='api.account')),
                ('new_entity', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='api.entity')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RecharacterizeChangeItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('change', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='api.recharacterizechange')),
                ('journal_entry_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='api.journalentryitem')),
                ('prior_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='api.account')),
                ('prior_entity', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='api.entity')),
            ],
        ),
    ]
