# Generated by Django 4.1.6 on 2023-04-14 13:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0037_transaction_tax_charge_alter_account_sub_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='tax_charge',
        ),
        migrations.CreateModel(
            name='TaxCharge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tax_type', models.CharField(choices=[('property', 'Property'), ('federal', 'Federal'), ('state', 'State')], max_length=25)),
                ('date', models.DateField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('transaction', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api.transaction')),
            ],
        ),
    ]
