# Generated by Django 4.1.6 on 2023-04-14 14:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0038_remove_transaction_tax_charge_taxcharge'),
    ]

    operations = [
        migrations.RenameField(
            model_name='taxcharge',
            old_name='tax_type',
            new_name='type',
        ),
        migrations.AlterUniqueTogether(
            name='taxcharge',
            unique_together={('type', 'date')},
        ),
    ]
