# Generated by Django 6.0.6 on 2026-07-22 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0038_rename_securities_retirement_to_restricted'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='account',
            name='unique_special_type_except_property_taxes',
        ),
        migrations.AlterField(
            model_name='account',
            name='special_type',
            field=models.CharField(blank=True, choices=[('unrealized_gains_and_losses', 'Unrealized Gains and Losses'), ('state_taxes_payable', 'State Taxes Payable'), ('federal_taxes_payable', 'Federal Taxes Payable'), ('property_taxes_payable', 'Property Taxes Payable'), ('state_taxes', 'State Taxes'), ('federal_taxes', 'Federal Taxes'), ('property_taxes', 'Property Taxes'), ('payroll_taxes', 'Payroll Taxes'), ('wallet', 'Wallet'), ('prepaid_expenses', 'Prepaid Expenses'), ('starting_equity', 'Starting Equity')], max_length=30, null=True),
        ),
        migrations.AddConstraint(
            model_name='account',
            constraint=models.UniqueConstraint(condition=models.Q(('special_type__in', ['property_taxes', 'prepaid_expenses', 'payroll_taxes']), _negated=True), fields=('special_type',), name='unique_special_type_except_property_taxes'),
        ),
    ]
