# Generated by Django 4.1.6 on 2023-04-16 18:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0039_rename_tax_type_taxcharge_type_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='taxcharge',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='taxcharge',
            name='type',
        ),
    ]
