# Generated by Django 6.0.6 on 2026-07-23 14:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0039_remove_account_unique_special_type_except_property_taxes_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PrefillItem',
        ),
    ]
