# Generated by Django 4.1.6 on 2023-04-16 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0040_alter_taxcharge_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='taxcharge',
            name='type',
            field=models.CharField(choices=[('property', 'Property'), ('federal', 'Federal'), ('state', 'State')], default='state', max_length=25),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='taxcharge',
            unique_together={('type', 'date')},
        ),
    ]
