# Generated by Django 4.1.6 on 2023-04-16 18:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0041_taxcharge_type_alter_taxcharge_unique_together'),
    ]

    operations = [
        migrations.RenameField(
            model_name='taxcharge',
            old_name='type',
            new_name='tax_type',
        ),
        migrations.AlterUniqueTogether(
            name='taxcharge',
            unique_together={('tax_type', 'date')},
        ),
    ]
