# Generated by Django 4.1.6 on 2023-04-17 11:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0042_rename_type_taxcharge_tax_type_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='taxcharge',
            old_name='tax_type',
            new_name='type',
        ),
        migrations.AlterUniqueTogether(
            name='taxcharge',
            unique_together=set(),
        ),
    ]
