# Generated by Django 6.0.6 on 2026-08-09 20:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0043_account_role_kind_constraints_remove_special_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='csvcolumnvaluepair',
            name='csv_profile',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='api.csvprofile'),
        ),
    ]
