# Generated by Django 4.1.6 on 2023-04-20 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0043_rename_tax_type_taxcharge_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='sub_type',
            field=models.CharField(choices=[('short_term_debt', 'Short-term Debt'), ('long_term_debt', 'Long-term Debt'), ('taxes_payable', 'Taxes Payable'), ('cash', 'Cash'), ('real_estate', 'Real Estate'), ('securities_retirement', 'Securities-Retirement'), ('securities_unrestricted', 'Securities-Unrestricted'), ('retained_earnings', 'Retained Earnings'), ('unrealized_investment_gains', 'Unrealized Investment Gains'), ('realized_investment_gains', 'Realized Investment Gains'), ('salary', 'Salary'), ('dividends_and_interest', 'Dividends & Interest'), ('other_income', 'Other Income'), ('purchases', 'Purchases'), ('tax', 'Tax'), ('interest', 'Interest Expense')], max_length=30),
        ),
    ]
