# Generated by Django 6.0.6 on 2026-08-09 20:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0045_backfill_csvcolumnvaluepair_csv_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='csvprofile',
            name='clear_values_column_pairs',
        ),
        migrations.AlterField(
            model_name='csvcolumnvaluepair',
            name='csv_profile',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='clear_values_column_pairs', to='api.csvprofile'),
            preserve_default=False,
        ),
    ]
