# Generated by Django 4.1.6 on 2023-05-03 20:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0046_transaction_suggested_account'),
    ]

    operations = [
        migrations.AddField(
            model_name='reconciliation',
            name='transaction',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.transaction'),
        ),
    ]
