# Generated by Django 6.0.6 on 2026-08-11 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0046_finalize_csvcolumnvaluepair_csv_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='csvprofile',
            name='positive_outflows',
            field=models.BooleanField(default=False),
        ),
    ]
