# Generated by Django 4.1.6 on 2023-05-06 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0047_reconciliation_transaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='special_type',
            field=models.CharField(blank=True, choices=[('unrealized_gains_and_losses', 'Unrealized Gains and Losses')], max_length=30, null=True, unique=True),
        ),
    ]
