# Generated by Django 6.0.6 on 2026-08-18 00:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0047_csvprofile_positive_outflows'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='s3file',
            name='textract_job_id',
        ),
    ]
