# Generated by Django 6.0.6 on 2026-09-05 18:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0049_backfill_s3file_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='s3file',
            name='analysis_complete',
        ),
    ]
