# Generated by Django 4.1.6 on 2023-07-23 16:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0050_alter_journalentry_transaction'),
    ]

    operations = [
        migrations.CreateModel(
            name='CSVColumnValuePair',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('column', models.CharField(max_length=200)),
                ('value', models.CharField(max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='csvprofile',
            name='clear_prepended_until_value',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='csvprofile',
            name='inflow',
            field=models.CharField(default='Amount', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='csvprofile',
            name='outflow',
            field=models.CharField(default='Amount', max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='account',
            name='sub_type',
            field=models.CharField(choices=[('short_term_debt', 'Short-term Debt'), ('long_term_debt', 'Long-term Debt'), ('taxes_payable', 'Taxes Payable'), ('cash', 'Cash'), ('real_estate', 'Real Estate'), ('securities_retirement', 'Securities-Retirement'), ('securities_unrestricted', 'Securities-Unrestricted'), ('retained_earnings', 'Retained Earnings'), ('unrealized_investment_gains', 'Unrealized Investment Gains'), ('realized_investment_gains', 'Realized Investment Gains'), ('salary', 'Salary'), ('dividends_and_interest', 'Dividends & Interest'), ('other_income', 'Other Income'), ('purchases', 'Purchases'), ('tax', 'Tax'), ('interest', 'Interest Expense'), ('accounts_receivable', 'Accounts Receivable')], max_length=30),
        ),
        migrations.AlterField(
            model_name='journalentry',
            name='transaction',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='journal_entry', to='api.transaction'),
        ),
        migrations.AddField(
            model_name='csvprofile',
            name='clear_values_column_pairs',
            field=models.ManyToManyField(blank=True, null=True, to='api.csvcolumnvaluepair'),
        ),
    ]
