# Generated by Django 6.0.6 on 2026-09-13 12:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0051_repair_account_type_from_sub_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loanpayment',
            name='remaining_balance',
        ),
    ]
