# Generated by Django 4.1.6 on 2023-08-02 20:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0051_csvcolumnvaluepair_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='csvprofile',
            name='account',
        ),
        migrations.RemoveField(
            model_name='csvprofile',
            name='amount',
        ),
    ]
