# Generated by Django 4.1.6 on 2023-11-11 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0053_csvprofile_date_format'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='special_type',
            field=models.CharField(blank=True, choices=[('unrealized_gains_and_losses', 'Unrealized Gains and Losses'), ('state_taxes_payable', 'State Taxes Payable'), ('federal_taxes_payable', 'Federal Taxes Payable'), ('property_taxes_payable', 'Property Taxes Payable'), ('state_taxes', 'State Taxes'), ('federal_taxes', 'Federal Taxes'), ('property_taxes', 'Property Taxes'), ('wallet', 'Wallet')], max_length=30, null=True, unique=True),
        ),
    ]
