# Generated by Django 4.1.6 on 2023-12-07 21:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0054_alter_account_special_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='special_type',
            field=models.CharField(blank=True, choices=[('unrealized_gains_and_losses', 'Unrealized Gains and Losses'), ('state_taxes_payable', 'State Taxes Payable'), ('federal_taxes_payable', 'Federal Taxes Payable'), ('property_taxes_payable', 'Property Taxes Payable'), ('state_taxes', 'State Taxes'), ('federal_taxes', 'Federal Taxes'), ('property_taxes', 'Property Taxes'), ('wallet', 'Wallet'), ('prepaid_expenses', 'Prepaid Expenses')], max_length=30, null=True, unique=True),
        ),
        migrations.CreateModel(
            name='Amortization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.PositiveIntegerField()),
                ('periods', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('closed', models.BooleanField(default=False)),
                ('description', models.CharField(max_length=200)),
                ('accrued_transaction', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='accrued_amortizations', to='api.transaction')),
                ('suggested_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.account')),
            ],
        ),
        migrations.AddField(
            model_name='transaction',
            name='amortization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='api.amortization'),
        ),
    ]
