# Generated by Django 4.1.6 on 2023-12-07 22:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0055_alter_account_special_type_amortization_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='amortization',
            old_name='closed',
            new_name='is_closed',
        ),
    ]
