# Generated by Django 4.1.6 on 2023-12-07 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0056_rename_closed_amortization_is_closed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='amortization',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
    ]
