# Generated by Django 4.1.6 on 2023-12-10 18:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0057_alter_amortization_amount'),
    ]

    operations = [
        migrations.CreateModel(
            name='Prefill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api.transaction')),
            ],
        ),
        migrations.CreateModel(
            name='PrefillItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('journal_entry_item_type', models.CharField(choices=[('debit', 'Debit'), ('credit', 'Credit')], max_length=25)),
                ('order', models.PositiveSmallIntegerField()),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.account')),
                ('prefill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.prefill')),
            ],
        ),
        migrations.AddField(
            model_name='autotag',
            name='prefill',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.prefill'),
        ),
    ]
