# Generated by Django 4.1.6 on 2023-12-25 17:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0062_alter_transaction_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='amortization',
            name='suggested_account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.account'),
        ),
        migrations.AlterField(
            model_name='journalentryitem',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.account'),
        ),
        migrations.AlterField(
            model_name='reconciliation',
            name='transaction',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='api.transaction'),
        ),
        migrations.AlterField(
            model_name='taxcharge',
            name='transaction',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='api.transaction'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.account'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='amortization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='api.amortization'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='prefill',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='api.prefill'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='suggested_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='suggested_account', to='api.account'),
        ),
    ]
