# Generated by Django 4.1.6 on 2024-02-07 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0064_account_is_closed_alter_account_sub_type'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['date'], name='date_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['account'], name='account_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['type'], name='type_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['is_closed'], name='is_closed_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['linked_transaction'], name='linked_transaction_idx'),
        ),
    ]
