# Generated by Django 4.1.6 on 2024-02-07 13:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0065_transaction_date_idx_transaction_account_idx_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='transaction',
            name='date_idx',
        ),
        migrations.RemoveIndex(
            model_name='transaction',
            name='account_idx',
        ),
        migrations.RemoveIndex(
            model_name='transaction',
            name='type_idx',
        ),
        migrations.RemoveIndex(
            model_name='transaction',
            name='is_closed_idx',
        ),
        migrations.RemoveIndex(
            model_name='transaction',
            name='linked_transaction_idx',
        ),
    ]
