# Generated by Django 4.1.6 on 2024-02-09 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0067_transaction_date_idx_transaction_account_idx_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='journalentryitem',
            index=models.Index(fields=['type'], name='jei_date_idx'),
        ),
        migrations.AddIndex(
            model_name='journalentryitem',
            index=models.Index(fields=['account'], name='jei_account_idx'),
        ),
    ]
