# Generated by Django 4.1.6 on 2024-07-12 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0068_journalentryitem_jei_date_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='S3File',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(unique=True)),
                ('user_filename', models.CharField(max_length=200)),
                ('s3_filename', models.CharField(max_length=200)),
            ],
        ),
    ]
