# Generated by Django 4.1.6 on 2024-07-12 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0069_s3file'),
    ]

    operations = [
        migrations.AddField(
            model_name='s3file',
            name='textract_job_id',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
