# Generated by Django 4.1.6 on 2024-07-15 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0070_s3file_textract_job_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocSearch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword', models.CharField(blank=True, max_length=200, null=True)),
                ('row', models.CharField(blank=True, max_length=200, null=True)),
                ('column', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
    ]
