# Generated by Django 4.1.6 on 2024-07-15 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0071_docsearch'),
    ]

    operations = [
        migrations.AddField(
            model_name='docsearch',
            name='table_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
