# Generated by Django 4.1.6 on 2024-07-15 19:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0072_docsearch_table_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='docsearch',
            name='account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.account'),
        ),
        migrations.AddField(
            model_name='docsearch',
            name='selection',
            field=models.CharField(blank=True, choices=[('Company', 'Company'), ('Begin Period', 'Begin Period'), ('End Period', 'End Period')], max_length=20, null=True),
        ),
    ]
