# Generated by Django 4.1.6 on 2024-07-16 14:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0073_docsearch_account_docsearch_selection'),
    ]

    operations = [
        migrations.CreateModel(
            name='Paystub',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_id', models.CharField(max_length=200)),
                ('title', models.CharField(max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='docsearch',
            name='prefill',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.PROTECT, to='api.prefill'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='s3file',
            name='prefill',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.PROTECT, to='api.prefill'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='PaystubValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.account')),
                ('paystub', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.paystub')),
            ],
        ),
        migrations.AddField(
            model_name='paystub',
            name='document',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.s3file'),
        ),
        migrations.AddField(
            model_name='paystub',
            name='journal_entry',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.prefill'),
        ),
    ]
