# Generated by Django 4.1.6 on 2024-07-18 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0075_alter_docsearch_prefill'),
    ]

    operations = [
        migrations.AddField(
            model_name='docsearch',
            name='journal_entry_item_type',
            field=models.CharField(choices=[('debit', 'Debit'), ('credit', 'Credit')], default='debit', max_length=25),
        ),
        migrations.AlterField(
            model_name='s3file',
            name='textract_job_id',
            field=models.CharField(default='whatever', max_length=200),
            preserve_default=False,
        ),
    ]
