# Generated by Django 4.1.6 on 2024-07-23 15:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0078_paystubvalue_journal_entry_item_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paystub',
            name='journal_entry',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.journalentry'),
        ),
        migrations.AlterField(
            model_name='paystubvalue',
            name='paystub',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paystub_values', to='api.paystub'),
        ),
    ]
