# Generated by Django 4.1.6 on 2024-07-23 16:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0079_alter_paystub_journal_entry_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='s3file',
            name='prefill',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.prefill'),
        ),
    ]
