# Generated by Django 4.1.6 on 2024-07-24 13:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0080_alter_s3file_prefill'),
    ]

    operations = [
        migrations.AlterField(
            model_name='docsearch',
            name='journal_entry_item_type',
            field=models.CharField(blank=True, choices=[('debit', 'Debit'), ('credit', 'Credit')], max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='paystub',
            name='document',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='api.s3file'),
        ),
    ]
