# Generated by Django 4.1.6 on 2024-07-26 11:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0081_alter_docsearch_journal_entry_item_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Entity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.URLField(unique=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='docsearch',
            options={'verbose_name_plural': 'doc searches'},
        ),
        migrations.AlterModelOptions(
            name='journalentry',
            options={'verbose_name_plural': 'journal entries'},
        ),
        migrations.AddField(
            model_name='journalentryitem',
            name='entity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.entity'),
        ),
    ]
