# Generated by Django 4.1.6 on 2024-08-13 10:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0084_alter_entity_options_alter_entity_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='amortization',
            name='accrued_transaction',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='amortization',
        ),
        migrations.AddField(
            model_name='amortization',
            name='accrued_journal_entry_item',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='accrued_journal_entry_items', to='api.journalentryitem'),
        ),
        migrations.AddField(
            model_name='journalentryitem',
            name='amortization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='journal_entry_items', to='api.amortization'),
        ),
        migrations.AlterField(
            model_name='account',
            name='sub_type',
            field=models.CharField(choices=[('short_term_debt', 'Short-term Debt'), ('taxes_payable', 'Taxes Payable'), ('long_term_debt', 'Long-term Debt'), ('accounts_payable', 'Accounts Payable'), ('cash', 'Cash'), ('accounts_receivable', 'Accounts Receivable'), ('prepaid_expenses', 'Prepaid Expenses'), ('securities_unrestricted', 'Securities-Unrestricted'), ('securities_retirement', 'Securities-Retirement'), ('real_estate', 'Real Estate'), ('retained_earnings', 'Retained Earnings'), ('salary', 'Salary'), ('dividends_and_interest', 'Dividends & Interest'), ('realized_investment_gains', 'Realized Investment Gains'), ('other_income', 'Other Income'), ('unrealized_investment_gains', 'Unrealized Investment Gains'), ('purchases', 'Purchases'), ('tax', 'Tax'), ('interest', 'Interest Expense')], max_length=30),
        ),
    ]
