# Generated by Django 4.1.6 on 2024-08-13 13:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0086_remove_journalentryitem_amortization_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='amortization',
        ),
        migrations.AddField(
            model_name='journalentryitem',
            name='amortization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='api.amortization'),
        ),
    ]
