# Generated by Django 4.1.6 on 2024-08-13 14:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0087_remove_transaction_amortization_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='amortization',
            name='accrued_journal_entry_item',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='accrued_journal_entry_item', to='api.journalentryitem'),
        ),
        migrations.AlterField(
            model_name='journalentryitem',
            name='amortization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='journal_entry_items', to='api.amortization'),
        ),
    ]
