# Generated by Django 4.1.6 on 2024-08-13 14:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0088_alter_amortization_accrued_journal_entry_item_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='journalentryitem',
            name='amortization',
        ),
        migrations.AddField(
            model_name='transaction',
            name='amortization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='transations', to='api.amortization'),
        ),
    ]
