name: Deploy

on:
  push:
    branches:
      - main

jobs:
  test:
    uses: ./.github/workflows/ci.yml

  deploy:
    name: deploy
    needs: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Deploy to Heroku
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
        run: |
          git push -f https://heroku:$HEROKU_API_KEY@git.heroku.com/fast-cliffs-86166.git HEAD:refs/heads/main
